apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APPLICATION_NAME}-vault-templates
  namespace: ${NAMESPACE}
data:
  apicert.tmpl: |
    {{ with secret "kv/integracion/API_CONNECT/public/${CERT_API_PUBLIC_KEY_NAME}.pem" }}{{ .Data.data.cert }}{{ end }}
  issuing.tmpl: |
    {{ with secret "kv/integracion/pki-bancolombia" }}{{ .Data.data.${CERT_ISSUING_NAME} }}{{ end }}
  root.tmpl: |
    {{ with secret "kv/integracion/pki-bancolombia" }}{{ .Data.data.${CERT_ROOT_NAME} }}{{ end }}
  api_issuing.tmpl: |
    {{ with secret "kv/integracion/pki-bancolombia" }}{{ .Data.data.${CERT_API_CONNECT_ISSUING_NAME} }}{{ end }}
  api_root.tmpl: |
    {{ with secret "kv/integracion/pki-bancolombia" }}{{ .Data.data.${CERT_API_CONNECT_ROOT_NAME} }}{{ end }}
  depositscert.tmpl: |
    {{ with secret "kv/integracion/OpenShift/deposits-services/certs/${CERT_PUBLIC_DEPOSITS_NAME}.cer" }}{{ .Data.data.cert }}{{ end }}
  key.tmpl: |
    {{ with secret "kv/integracion/OpenShift/deposits-services/secrets/${CERT_PRIVATE_DEPOSITS_NAME}.key" }}{{ .Data.data.key }}{{ end }}
  pass.tmpl: |
    {{ with secret "kv/integracion/OpenShift/deposits-services/secrets/${CERT_PRIVATE_DEPOSITS_NAME}.key" }}{{ .Data.data.pass }}{{ end }}
