apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  labels:
    app: ${APPLICATION_NAME}
  name: ${APPLICATION_NAME}-autoscaling
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${APPLICATION_NAME}
  metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory 
      target:
        type: Utilization 
        averageUtilization: 90
