kind: Secret
apiVersion: v1
metadata:
  name: ${APPLICATION_NAME}-keys-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${APPLICATION_NAME}
data:
  CAMEL_KEYSTORE_PASSWORD: ${CAMEL_KEYSTORE_PASSWORD_BASE64}
  CAMEL_TRUSTSTORE_PASSWORD: ${CAMEL_TRUSTSTORE_PASSWORD_BASE64}