apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${APPLICATION_NAME}
  name: ${APPLICATION_NAME}
  namespace: ${NAMESPACE}
spec:
  ports:
    - name: 4180-tcp
      protocol: TCP
      port: 4180
      targetPort: 4180
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ${APPLICATION_NAME}
  sessionAffinity: None
  type: ClusterIP
